# Generated by Django 2.1.7 on 2020-04-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0002_auto_20200429_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la tâche')),
            ],
            options={
                'verbose_name': 'statut',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nom de la tâche')),
                ('description', models.TextField(null=True, verbose_name='Description de la tâche')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now,
                                                    verbose_name='Date de commencement de la tâche')),
                ('due_date',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de rendu de la tâche')),
                ('priority', models.IntegerField(default=0, verbose_name='Priorité de la tâche')),
                ('assignee', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL,
                                               verbose_name='Personne réalisant la tâche')),
                ('project', models.ForeignKey(on_delete='CASCADE', to='taskmanager.Project',
                                              verbose_name='Projet rattaché à la tâche')),
                ('status', models.ForeignKey(null=True, on_delete='SET_NULL', to='taskmanager.Status',
                                             verbose_name='Statut de la tâche')),
            ],
            options={
                'verbose_name': 'tâche',
                'ordering': ['status'],
            },
        ),
    ]
