# Generated by Django 2.1.7 on 2020-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskmanager', '0003_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Description de la tâche'),
            preserve_default=False,
        ),
    ]
